import { FishType } from './types';

export const GAME_DURATION = 90;
export const HOOK_DROP_SPEED = 250;
export const HOOK_RETRACT_SPEED = 300;
export const HOOK_X_RATIO = 0.35;
export const WATER_LEVEL_RATIO = 0.3;
export const FISH_SPAWN_INTERVAL_MIN = 0.8;
export const FISH_SPAWN_INTERVAL_MAX = 2.5;
export const MAX_FISHES = 15;
export const COMBO_DECAY_TIME = 5;
export const DEPTH_BONUS_MAX = 0.15;
export const SPEED_INCREASE_PER_SECOND = 0.003;

// 小鱼：速度快、浅水区；大鱼：速度慢、深水区
export const FISH_TYPES: FishType[] = [
  {
    name: '小丑鱼',
    nameEn: 'clownfish',
    radius: 15,
    width: 30,
    height: 18,
    speedMin: 100,
    speedMax: 150,
    score: 10,
    color: '#FF6B35',
    bodyColor: '#FF6B35',
    finColor: '#FFD700',
    spawnWeight: 30,
    waveAmplitude: 8,
    waveFrequency: 2,
    depthMin: 0,
    depthMax: 0.35,
  },
  {
    name: '蓝鲫鱼',
    nameEn: 'blueCrucian',
    radius: 18,
    width: 36,
    height: 20,
    speedMin: 80,
    speedMax: 130,
    score: 20,
    color: '#4A90D9',
    bodyColor: '#4A90D9',
    finColor: '#7BB8F0',
    spawnWeight: 25,
    waveAmplitude: 10,
    waveFrequency: 1.8,
    depthMin: 0.05,
    depthMax: 0.45,
  },
  {
    name: '金鱼',
    nameEn: 'goldfish',
    radius: 20,
    width: 40,
    height: 22,
    speedMin: 70,
    speedMax: 110,
    score: 30,
    color: '#FFD700',
    bodyColor: '#FFD700',
    finColor: '#FFA500',
    spawnWeight: 18,
    waveAmplitude: 12,
    waveFrequency: 1.5,
    depthMin: 0.15,
    depthMax: 0.55,
  },
  {
    name: '河豚',
    nameEn: 'pufferfish',
    radius: 25,
    width: 35,
    height: 30,
    speedMin: 40,
    speedMax: 70,
    score: 40,
    color: '#7ED321',
    bodyColor: '#7ED321',
    finColor: '#5CAE15',
    spawnWeight: 12,
    waveAmplitude: 6,
    waveFrequency: 2.5,
    depthMin: 0.35,
    depthMax: 0.7,
  },
  {
    name: '剑鱼',
    nameEn: 'swordfish',
    radius: 30,
    width: 60,
    height: 18,
    speedMin: 120,
    speedMax: 180,
    score: 80,
    color: '#C0C0C0',
    bodyColor: '#A8B8C8',
    finColor: '#8090A0',
    spawnWeight: 8,
    waveAmplitude: 15,
    waveFrequency: 3,
    depthMin: 0.3,
    depthMax: 0.75,
  },
  {
    name: '鲨鱼',
    nameEn: 'shark',
    radius: 40,
    width: 80,
    height: 30,
    speedMin: 50,
    speedMax: 90,
    score: 150,
    color: '#607080',
    bodyColor: '#607080',
    finColor: '#4A5A6A',
    spawnWeight: 4,
    waveAmplitude: 20,
    waveFrequency: 1,
    depthMin: 0.55,
    depthMax: 0.95,
  },
  {
    name: '金龙鱼',
    nameEn: 'goldenDragon',
    radius: 22,
    width: 50,
    height: 20,
    speedMin: 140,
    speedMax: 200,
    score: 200,
    color: '#FFD700',
    bodyColor: '#FFD700',
    finColor: '#FF8C00',
    spawnWeight: 3,
    waveAmplitude: 25,
    waveFrequency: 2,
    depthMin: 0.6,
    depthMax: 0.95,
    glow: true,
  },
];

export const TOTAL_SPAWN_WEIGHT = FISH_TYPES.reduce((sum, t) => sum + t.spawnWeight, 0);

export const COLORS = {
  skyTop: '#FF7E5F',
  skyBottom: '#FEB47B',
  waterTop: '#0EA5E9',
  waterMid: '#0369A1',
  waterBottom: '#0C2D48',
  sunColor: '#FFE066',
  cloudColor: 'rgba(255,255,255,0.7)',
  sandColor: '#C4A35A',
  seaweedColor1: '#2D8B46',
  seaweedColor2: '#1E6B33',
  seaweedColor3: '#3DA85C',
  lineColor: '#E0E0E0',
  hookColor: '#C0C0C0',
  pierColor: '#8B6914',
  pierDark: '#6B4F10',
};
